[workspace]
resolver = "2"
members = ["crates/qw-core", "crates/qw-dsp", "crates/qw-audio", "crates/qw-macos", "crates/qw-linux", "crates/qw-windows"]
default-members = ["crates/qw-core"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
rust-version = "1.74"
authors = ["Chris Perriello <chrisperriello00@gmail.com>"]
publish = false

[workspace.dependencies]
qw-core = { path = "crates/qw-core" }
qw-dsp = { path = "crates/qw-dsp" }
qw-audio = { path = "crates/qw-audio" }
qw-macos = { path = "crates/qw-macos" }
qw-linux = { path = "crates/qw-linux" }
qw-windows = { path = "crates/qw-windows" }
